# Generated by Django 5.2.7 on 2025-10-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Blog Categories'},
        ),
    ]
